baseURL = "https://soul-coder-heap.github.io"
title = "The world of the coder."

languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

SectionPagesMenu = "main"
Paginate = 25 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

DefaultContentLanguage = "en"
copyright = "Nothing is Mine"

defaultContentLanguageInSubdirto = true
sectionPagesMenu = "smain"

[languages]
  [languages.en]
    LanguageName = "English"
    weight = 1
    contentDir = "content/en/"
    [languages.en.params]
      linkedin = "https://www.linkedin.cn/incareer/in/ACoAAD8GrHoBv7ebk3jukkNFUA7iJPJWd_WwDA0"
      #cover_dimming_class = "bg-black-80"
      github = "https://github.com/soul-coder-heap"
#  [languages.zh]
#    LanguageName = "中文"
#    weight = 1
#    contentDir = "content/cn/"
#    [languages.zh.params]
#      linkedin = "https://www.linkedin.cn/incareer/in/ACoAAD8GrHoBv7ebk3jukkNFUA7iJPJWd_WwDA0"
#      #cover_dimming_class = "bg-black-80"
#      github = "https://github.com/soul-coder-heap"


[menu]
  [[menu.main]]
    identifier = "program"
    name = "前后端-算法-架构"
    weight = 1
    url = "/program/"
    # languageDirection = 'rtl' for Right-To-Left languages
  [[menu.main]]
    identifier = "ml"
    name = "机器学习"
    weight = 2
    url = "/ml/"
  [[menu.main]]
    identifier = "cv"
    name = "计算机视觉"
    weight = 3
    url = "/cv/"
  [[menu.main]]
    identifier = "driver"
    name = "自动驾驶"
    weight = 4
    url = "/driver/"
  [[menu.main]]
    identifier = "quantitative_trading"
    name = "量化交易"
    weight = 5
    url = "/quantitative_trading/"
  [[menu.main]]
    identifier = "arts"
    name = "艺术鉴赏"
    weight = 6
    url = "/arts/"
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 7

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 25

#[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/GoHugoIO"
