baseURL = "https://soul-coder-heap.github.io"
title = "YF-New-Hugo-Site"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = '编程语言'
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.'算法']
    title = "算法"
    weight = 1
    contentDir = "content/algo"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.'机器学习']
    title = "机器学习"
    weight = 2
    contentDir = "content/ml"
  [languages.'计算机视觉']
    title = "计算机视觉"
    weight = 3
    contentDir = "content/cv"
  [languages.'编程语言']
    title = "编程语言"
    weight = 4
    contentDir = "content/program"
  [languages.'自动驾驶']
    title = "自动驾驶"
    weight = 5
    contentDir = "content/driver"
  [languages.'呦呦酱']
    title = "呦呦"
    weight = 6
    contentDir = "content/youyou"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 10

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
